use_frameworks!

platform :ios, '9.0'

target 'CGPodTest_Example' do
  pod 'CGPodTest', :path => '../'

  target 'CGPodTest_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
